print("hello m.6/11")
print("my name is phureetud")
print("No.9")
print("อายุ :",16,"ปี")
print("เกิดที่ชลบุรี")
print("เรียนที่ชลราษฎรอำรุง")
print("เบอร์โทร0952108383")
print("ที่บ้านอยู่กัน5คน")
print("ชอบกินเนื้อ")
print("ชื่อเล่น นนท์")